INSERT INTO "AdPlacement" ("id", "key", "name", "inventoryFamily", "format", "enabled", "config", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid(), 'home_top', 'Home top', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/"],"sizes":[[970,90],[728,90],[320,100]],"responsive":[{"minWidth":1024,"sizes":[[970,90],[728,90]]},{"minWidth":0,"sizes":[[320,100],[320,50]]}],"devices":["MOBILE","DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'home_between_rows', 'Home between rows', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/"],"sizes":[[970,250],[728,90],[300,250]],"responsive":[{"minWidth":1024,"sizes":[[970,250],[728,90]]},{"minWidth":0,"sizes":[[300,250]]}],"devices":["MOBILE","DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'watch_below_player', 'Watch below player', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/watch/*"],"sizes":[[728,90],[300,250]],"responsive":[{"minWidth":768,"sizes":[[728,90]]},{"minWidth":0,"sizes":[[300,250]]}],"devices":["MOBILE","DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'content_detail', 'Content detail', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/movies/*","/series/*"],"sizes":[[728,90],[300,250]],"responsive":[],"devices":["MOBILE","DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'search_between_results', 'Search between results', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/search*"],"sizes":[[728,90],[300,250]],"responsive":[],"devices":["MOBILE","DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'channel_between_rows', 'Channel between rows', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/c/*"],"sizes":[[728,90],[300,250]],"responsive":[],"devices":["MOBILE","DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'tv_directory', 'TV directory', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["/tv"],"sizes":[[970,90],[728,90],[320,100]],"responsive":[],"devices":["MOBILE","DESKTOP","TV"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now()),
  (gen_random_uuid(), 'desktop_sidebar', 'Desktop sidebar', 'OUTSIDE_PLAYER', 'DISPLAY', false, '{"routePatterns":["*"],"sizes":[[300,600],[300,250]],"responsive":[],"devices":["DESKTOP"],"audience":"ANY","categories":[],"demand":{"source":"GOOGLE_GPT","adUnitPath":null},"fallback":"COLLAPSE"}'::jsonb, now(), now())
ON CONFLICT ("key") DO NOTHING;
