"use client";
import { useCallback } from "react";
import { useI18n } from "@/components/i18n/i18n-provider";

const ar: Record<string, string> = {
  "The outcome is uncertain. Reopen a saved record to review it before making another change. No request was repeated.":
    "نتيجة الطلب غير مؤكدة. أعد فتح السجل المحفوظ لمراجعته قبل أي تعديل آخر. لم يتكرر أي طلب.",
  "Search results could not be verified. Try searching again.":
    "تعذر التحقق من نتائج البحث. حاول البحث مجددًا.",
  "Catalog operations": "إدارة المكتبة",
  Movies: "الأفلام",
  Series: "المسلسلات",
  "Draft, validate and publish movie identities without exposing database IDs or unsafe media.":
    "أنشئ مسودات الأفلام وتحقق من جاهزيتها قبل النشر.",
  "Manage Series, Seasons and Episodes as deliberate catalog records. Playable media is selected by title and channel context, while internal database identifiers stay hidden.":
    "أدر المسلسلات والمواسم والحلقات، واختر وسائط التشغيل بالعنوان والقناة.",
  "New movie draft": "مسودة فيلم جديدة",
  "New series draft": "مسودة مسلسل جديدة",
  "Edit movie": "تعديل الفيلم",
  "Edit series": "تعديل المسلسل",
  "Create draft": "إنشاء مسودة",
  "New movie": "فيلم جديد",
  "New series": "مسلسل جديد",
  DRAFT: "مسودة",
  PUBLISHED: "منشور",
  ARCHIVED: "مؤرشف",
  Draft: "مسودة",
  Published: "منشور",
  Archived: "مؤرشف",
  "Validation:": "التحقق:",
  Validation: "التحقق",
  Title: "العنوان",
  Slug: "اسم الرابط",
  "generated from title when blank": "يُنشأ من العنوان عند تركه فارغًا",
  Synopsis: "الملخص",
  "Release year": "سنة الإصدار",
  "Runtime (minutes)": "المدة بالدقائق",
  "Release date": "تاريخ الإصدار",
  Maturity: "التصنيف العمري",
  "Original language": "اللغة الأصلية",
  "Genres / categories": "الأنواع / الفئات",
  "Drama, Mystery": "دراما، غموض",
  "Primary playback": "الفيديو الأساسي",
  Trailer: "الإعلان التشويقي",
  "Series trailer": "إعلان المسلسل",
  Availability: "الإتاحة",
  "Use * for global rights or a two-letter territory code.":
    "استخدم * للحقوق العالمية أو رمز منطقة من حرفين.",
  "Leave empty for unrestricted Series availability, or add explicit global/territory rules with optional windows.":
    "اتركها فارغة للإتاحة دون قيود، أو أضف قواعد عالمية أو إقليمية بفترات اختيارية.",
  "Add rule": "إضافة قاعدة",
  Territory: "المنطقة",
  Rule: "القاعدة",
  Allow: "سماح",
  Block: "حظر",
  Starts: "البداية",
  Ends: "النهاية",
  Note: "ملاحظة",
  "Remove rule": "إزالة القاعدة",
  "Saving…": "جارٍ الحفظ…",
  "Save movie": "حفظ الفيلم",
  "Save series": "حفظ المسلسل",
  Unpublish: "إلغاء النشر",
  Publish: "نشر",
  Archive: "أرشفة",
  "Publish series": "نشر المسلسل",
  "Unpublish series": "إلغاء نشر المسلسل",
  "Catalog browser": "تصفح المكتبة",
  results: "نتيجة",
  "Search title, slug, synopsis or genre…": "ابحث بالعنوان أو الرابط أو الملخص أو النوع…",
  "All statuses": "كل الحالات",
  "min ·": "دقيقة ·",
  "No genres": "لا توجد أنواع",
  "Primary:": "الفيديو الأساسي:",
  "Not assigned": "غير معيّن",
  Edit: "تعديل",
  Manage: "إدارة",
  Ready: "جاهز",
  READY: "جاهز",
  Optional: "اختياري",
  "Season & episode management": "إدارة المواسم والحلقات",
  "Ordering is conflict-safe. Episodes must reference an accessible playable Video before publication.":
    "يُتحقق من ترتيب العناصر. يجب ربط الحلقات بفيديو متاح للتشغيل قبل النشر.",
  seasons: "مواسم",
  Season: "موسم",
  "· catalog position": "· الترتيب",
  episodes: "حلقات",
  "No episodes in this season yet.": "لا توجد حلقات في هذا الموسم بعد.",
  "Add the first season to start episode management.": "أضف الموسم الأول لبدء إدارة الحلقات.",
  Status: "الحالة",
  Seasons: "المواسم",
  Episodes: "الحلقات",
  Action: "الإجراء",
  "year unset": "السنة غير محددة",
  "No series match these filters.": "لا توجد مسلسلات مطابقة لهذه المرشحات.",
  "Add season": "إضافة موسم",
  "Create the season as a catalog child; artwork is optional.":
    "أضف موسمًا للمسلسل. الصور اختيارية.",
  "Season number": "رقم الموسم",
  "Season poster": "ملصق الموسم",
  "Season title": "عنوان الموسم",
  "Save season metadata": "حفظ بيانات الموسم",
  "Add episode": "إضافة حلقة",
  "Draft episodes may omit playback; publication requires a playable Video.":
    "يمكن إنشاء مسودة دون فيديو؛ يتطلب النشر فيديو قابلًا للتشغيل.",
  "Episode number": "رقم الحلقة",
  "Episode playback": "فيديو الحلقة",
  "Add episode draft": "إضافة مسودة حلقة",
  E: "ح",
  "playback not assigned": "الفيديو غير معيّن",
  "Save episode": "حفظ الحلقة",
  "Publish episode": "نشر الحلقة",
  "Unpublish episode": "إلغاء نشر الحلقة",
  "Ready to publish": "جاهز للنشر",
  "Only accessible published videos with validated playback are selectable.":
    "يمكن اختيار الفيديوهات المنشورة والمتاحة ذات التشغيل المتحقق منه فقط.",
  "Only validated, non-removed image assets are selectable.":
    "يمكن اختيار الصور المتحقق منها وغير المحذوفة فقط.",
  "Required to publish": "مطلوب للنشر",
  "Selected catalog resource": "المورد المختار",
  "Selection is stored internally; database IDs are hidden.":
    "يُحفظ الاختيار داخليًا دون إظهار معرّفات قاعدة البيانات.",
  Clear: "مسح",
  "Required while published": "مطلوب أثناء النشر",
  "Search title, slug or channel…": "ابحث بالعنوان أو الرابط أو القناة…",
  "Search asset, video or channel…": "ابحث بالصورة أو الفيديو أو القناة…",
  "Searching…": "جارٍ البحث…",
  Select: "اختيار",
  Search: "بحث",
  "Search movies": "البحث عن أفلام",
  "Search series": "البحث عن مسلسلات",
  "Filter by status": "تصفية حسب الحالة",
  "Refresh list": "تحديث القائمة",
  "Refresh record": "تحديث السجل",
  "Movie details": "بيانات الفيلم",
  "Series details": "بيانات المسلسل",
  "Season details": "بيانات الموسم",
  "Episode details": "بيانات الحلقة",
  "New season": "موسم جديد",
  "New episode": "حلقة جديدة",
  "Movie catalog could not be loaded.": "تعذر تحميل مكتبة الأفلام.",
  "Series catalog could not be loaded.": "تعذر تحميل مكتبة المسلسلات.",
  "Search failed.": "تعذر البحث.",
  "Changes were saved, but the catalog list could not refresh. Use Refresh list; do not submit again.":
    "حُفظت التغييرات، لكن تعذر تحديث القائمة. استخدم تحديث القائمة ولا ترسل الطلب مجددًا.",
  "Changes were saved, but the catalog could not refresh. Use Refresh record; do not submit again.":
    "حُفظت التغييرات، لكن تعذر تحديث المكتبة. استخدم تحديث السجل ولا ترسل الطلب مجددًا.",
  "The save result could not be verified. Refresh before trying again.":
    "تعذر التحقق من نتيجة الحفظ. حدّث السجل قبل المحاولة مجددًا.",
  "The outcome is uncertain. Refresh the record before trying again.":
    "نتيجة الطلب غير مؤكدة. حدّث السجل قبل المحاولة مجددًا.",
  "The selected record could not be verified.": "تعذر التحقق من السجل المختار.",
  "Movie changes saved.": "حُفظت تعديلات الفيلم.",
  "Movie draft created.": "أُنشئت مسودة الفيلم.",
  "Series changes saved.": "حُفظت تعديلات المسلسل.",
  "Series draft created.": "أُنشئت مسودة المسلسل.",
  "Movie published.": "نُشر الفيلم.",
  "Movie unpublished.": "أُلغي نشر الفيلم.",
  "Movie archived.": "أُرشف الفيلم.",
  "Series published.": "نُشر المسلسل.",
  "Series unpublished.": "أُلغي نشر المسلسل.",
  "Series archived.": "أُرشف المسلسل.",
  "Change movie status?": "تغيير حالة الفيلم؟",
  "Change series status?": "تغيير حالة المسلسل؟",
  "This changes the saved record’s public availability.": "سيغيّر هذا إتاحة السجل المحفوظ للجمهور.",
  Confirm: "تأكيد",
  Cancel: "إلغاء",
  "Season ordering updated.": "حُدّث ترتيب المواسم.",
  "Episode ordering updated.": "حُدّث ترتيب الحلقات.",
  "Season created.": "أُنشئ الموسم.",
  "Season saved.": "حُفظ الموسم.",
  "Episode created.": "أُنشئت الحلقة.",
  "Episode saved.": "حُفظت الحلقة.",
  "Episode published.": "نُشرت الحلقة.",
  "Episode unpublished.": "أُلغي نشر الحلقة.",
  "Poster artwork": "صورة الملصق",
  "Backdrop artwork": "صورة الخلفية",
  "Logo artwork": "صورة الشعار",
  "Season Poster": "ملصق الموسم",
  "Season Backdrop": "خلفية الموسم",
  "Season Logo": "شعار الموسم",
  "Move up": "نقل لأعلى",
  "Move down": "نقل لأسفل",
  "validation issues": "مشكلات تحقق",
  "No matching resources.": "لا توجد موارد مطابقة.",
  "Unsaved changes": "تغييرات غير محفوظة",
  "Save changes before changing status.": "احفظ التغييرات قبل تغيير الحالة.",
};
export function useCatalogCopy() {
  const { locale } = useI18n();
  return useCallback((value: string) => (locale === "ar" ? (ar[value] ?? value) : value), [locale]);
}
