import { z } from "zod";

export const platformSettingCatalog = {
  registrationEnabled: {
    namespace: "PLATFORM",
    key: "registrationEnabled",
    valueType: "BOOLEAN",
    defaultValue: true,
    schema: z.boolean(),
    section: "access",
    label: "Registration enabled",
    description: "Allow new AYIN accounts to register.",
    control: "toggle",
    highImpact: true,
    superadminOnly: false,
  },
  automaticCreatorProvisioningEnabled: {
    namespace: "CREATOR",
    key: "automaticCreatorProvisioningEnabled",
    valueType: "BOOLEAN",
    defaultValue: true,
    schema: z.boolean(),
    section: "access",
    label: "Automatic creator provisioning",
    description:
      "Creates the default profile, channel, Uploads playlist and Creator TV during registration. Disabling this blocks new registration rather than allowing partial identities.",
    control: "toggle",
    highImpact: true,
    superadminOnly: true,
  },
  maintenanceMode: {
    namespace: "PLATFORM",
    key: "maintenanceMode",
    valueType: "BOOLEAN",
    defaultValue: false,
    schema: z.boolean(),
    section: "access",
    label: "Maintenance mode",
    description: "Operational maintenance switch for AYIN surfaces that consume it.",
    control: "toggle",
    highImpact: true,
    superadminOnly: true,
  },
  uploadsPlaylistName: {
    namespace: "CREATOR",
    key: "uploadsPlaylistName",
    valueType: "STRING",
    defaultValue: "Uploads",
    schema: z.string().trim().min(1).max(80),
    section: "creatorDefaults",
    label: "Default Uploads playlist name",
    description: "Name of the protected system Uploads playlist created for new creators.",
    control: "text",
    highImpact: false,
    superadminOnly: false,
  },
  allowCreatorUploadsPlaylistRename: {
    namespace: "CREATOR",
    key: "allowCreatorUploadsPlaylistRename",
    valueType: "BOOLEAN",
    defaultValue: true,
    schema: z.boolean(),
    section: "creatorDefaults",
    label: "Creators can rename Uploads",
    description:
      "Allow channel owners to rename the protected Uploads playlist while AYIN keeps its system identity and automatic membership behavior.",
    control: "toggle",
    highImpact: false,
    superadminOnly: false,
  },
  creatorTvNameTemplate: {
    namespace: "TV",
    key: "creatorTvNameTemplate",
    valueType: "STRING",
    defaultValue: "{channelName} TV",
    schema: z
      .string()
      .trim()
      .min(3)
      .max(120)
      .refine((value) => value.includes("{channelName}"), {
        message: "Creator TV template must include {channelName}.",
      }),
    section: "creatorDefaults",
    label: "Creator TV name template",
    description: "Template for new Creator TVs. Keep the {channelName} token.",
    control: "text",
    highImpact: false,
    superadminOnly: false,
  },
  autoAddPublishedUploadsToCreatorTv: {
    namespace: "TV",
    key: "autoAddPublishedUploadsToCreatorTv",
    valueType: "BOOLEAN",
    defaultValue: true,
    schema: z.boolean(),
    section: "creatorDefaults",
    label: "Auto-add published uploads to Creator TV",
    description:
      "Published public MP4 videos enter automatic Creator TV rotation unless channel or video-level controls exclude them.",
    control: "toggle",
    highImpact: false,
    superadminOnly: false,
  },
  creatorTvFallbackProgramDurationMs: {
    namespace: "TV",
    key: "creatorTvFallbackProgramDurationMs",
    valueType: "INTEGER",
    defaultValue: 15 * 60 * 1000,
    schema: z
      .number()
      .int()
      .min(30 * 1000)
      .max(6 * 60 * 60 * 1000),
    section: "creatorDefaults",
    label: "Creator TV fallback program duration",
    description:
      "Duration used only when a published MP4 has no reliable duration metadata. Real video duration wins whenever available.",
    control: "number",
    unit: "ms",
    highImpact: false,
    superadminOnly: false,
  },
  creatorTvGuideWindowMinutes: {
    namespace: "TV",
    key: "creatorTvGuideWindowMinutes",
    valueType: "INTEGER",
    defaultValue: 240,
    schema: z.number().int().min(30).max(1440),
    section: "creatorDefaults",
    label: "Creator TV rolling guide window",
    description: "How many future minutes the V1 application-level Creator TV guide calculates.",
    control: "number",
    unit: "minutes",
    highImpact: false,
    superadminOnly: false,
  },
  creatorTvRotationMode: {
    namespace: "TV",
    key: "creatorTvRotationMode",
    valueType: "STRING",
    defaultValue: "PRIORITY_ORDER_OLDEST",
    schema: z.enum(["PRIORITY_ORDER_OLDEST", "PRIORITY_ORDER_NEWEST"]),
    section: "creatorDefaults",
    label: "Creator TV default rotation mode",
    description:
      "Deterministic fallback order after creator priority and explicit order controls are applied.",
    control: "select",
    options: ["PRIORITY_ORDER_OLDEST", "PRIORITY_ORDER_NEWEST"],
    highImpact: false,
    superadminOnly: false,
  },
  watchProgressSaveIntervalSeconds: {
    namespace: "DISCOVERY",
    key: "watchProgressSaveIntervalSeconds",
    valueType: "INTEGER",
    defaultValue: 15,
    schema: z.number().int().min(5).max(120),
    section: "watching",
    label: "Watch progress save interval",
    description:
      "Minimum routine interval between Continue Watching progress checkpoints. Pause, end and page-exit checkpoints may save sooner.",
    control: "number",
    unit: "seconds",
    highImpact: false,
    superadminOnly: false,
  },
  watchCompletionThresholdPercent: {
    namespace: "DISCOVERY",
    key: "watchCompletionThresholdPercent",
    valueType: "INTEGER",
    defaultValue: 90,
    schema: z.number().int().min(50).max(100),
    section: "watching",
    label: "Watch completion threshold",
    description:
      "Percentage of a known video duration at which AYIN marks the viewer profile's progress completed.",
    control: "number",
    unit: "%",
    highImpact: false,
    superadminOnly: false,
  },
  defaultVideoVisibility: {
    namespace: "CREATOR",
    key: "defaultVideoVisibility",
    valueType: "STRING",
    defaultValue: "PUBLIC",
    schema: z.enum(["PUBLIC", "UNLISTED", "PRIVATE"]),
    section: "contentDefaults",
    label: "Default video visibility",
    description: "Visibility preselected for new creator videos.",
    control: "select",
    options: ["PUBLIC", "UNLISTED", "PRIVATE"],
    highImpact: false,
    superadminOnly: false,
  },
  defaultCommentsEnabled: {
    namespace: "CREATOR",
    key: "defaultCommentsEnabled",
    valueType: "BOOLEAN",
    defaultValue: true,
    schema: z.boolean(),
    section: "contentDefaults",
    label: "Default comments enabled",
    description: "Whether comments are enabled by default for new creator videos.",
    control: "toggle",
    highImpact: false,
    superadminOnly: false,
  },
  moderationDefaultMode: {
    namespace: "MODERATION",
    key: "moderationDefaultMode",
    valueType: "STRING",
    defaultValue: "STANDARD",
    schema: z.enum(["LIGHT", "STANDARD", "STRICT"]),
    section: "contentDefaults",
    label: "Moderation default mode",
    description: "Default moderation posture for new content/community surfaces.",
    control: "select",
    options: ["LIGHT", "STANDARD", "STRICT"],
    highImpact: false,
    superadminOnly: false,
  },
  uploadMaxSizeBytes: {
    namespace: "UPLOAD",
    key: "uploadMaxSizeBytes",
    valueType: "INTEGER",
    defaultValue: 5 * 1024 * 1024 * 1024,
    schema: z
      .number()
      .int()
      .min(100 * 1024 * 1024)
      .max(50 * 1024 * 1024 * 1024),
    section: "uploads",
    label: "Upload max size",
    description: "Maximum source-video upload size in bytes.",
    control: "number",
    unit: "bytes",
    highImpact: false,
    superadminOnly: false,
  },
  uploadChannelQuotaBytes: {
    namespace: "UPLOAD",
    key: "uploadChannelQuotaBytes",
    valueType: "INTEGER",
    defaultValue: 100 * 1024 * 1024 * 1024,
    schema: z
      .number()
      .int()
      .min(1024 * 1024 * 1024)
      .max(10 * 1024 * 1024 * 1024 * 1024),
    section: "uploads",
    label: "Channel upload storage allowance",
    description:
      "Maximum active source-video bytes reserved by a channel across pending and uploaded assets.",
    control: "number",
    unit: "bytes",
    highImpact: false,
    superadminOnly: false,
  },
  initialMediaCompatibilityProfileText: {
    namespace: "UPLOAD",
    key: "initialMediaCompatibilityProfileText",
    valueType: "STRING",
    defaultValue: "MP4 using H.264/AVC video and AAC audio, up to 1080p",
    schema: z.string().trim().min(10).max(240),
    section: "uploads",
    label: "Initial media compatibility profile",
    description: "Creator-facing display text for the V1 playback-ready MP4 compatibility profile.",
    control: "textarea",
    highImpact: false,
    superadminOnly: false,
  },
  defaultMonetizationAdEligibility: {
    namespace: "MONETIZATION",
    key: "defaultMonetizationAdEligibility",
    valueType: "BOOLEAN",
    defaultValue: false,
    schema: z.boolean(),
    section: "monetization",
    label: "Default monetization / ad eligibility",
    description:
      "Default eligibility for newly created content. Safe bootstrap default is disabled.",
    control: "toggle",
    highImpact: true,
    superadminOnly: false,
  },
  defaultCreatorRevenueShareBps: {
    namespace: "MONETIZATION",
    key: "defaultCreatorRevenueShareBps",
    valueType: "INTEGER",
    defaultValue: 0,
    schema: z.number().int().min(0).max(10_000),
    section: "monetization",
    label: "Default creator revenue share",
    description: "Creator revenue share in basis points (10,000 = 100%).",
    control: "number",
    unit: "bps",
    highImpact: true,
    superadminOnly: false,
  },
} as const;

export type PlatformSettingKey = keyof typeof platformSettingCatalog;

export const platformSettingKeys = Object.keys(platformSettingCatalog) as PlatformSettingKey[];

export const platformSettingSections = [
  { id: "access", label: "Access & platform state" },
  { id: "creatorDefaults", label: "Creator defaults" },
  { id: "contentDefaults", label: "Content & moderation defaults" },
  { id: "watching", label: "Watching & Continue Watching" },
  { id: "uploads", label: "Uploads & compatibility" },
  { id: "monetization", label: "Monetization defaults" },
] as const;

export function isPlatformSettingKey(value: string): value is PlatformSettingKey {
  return Object.prototype.hasOwnProperty.call(platformSettingCatalog, value);
}
