import type { Locale } from "./i18n/config";
const arabic: Record<string, string> = {
  "Upload a video": "رفع فيديو",
  "Choose a format and file, review the details, then save or publish your video.":
    "اختر نوع الفيديو والملف، ثم راجع التفاصيل واحفظها أو انشر الفيديو.",
  "Creator upload": "رفع الفيديو",
  "Bring your next video to AYIN.": "ارفع فيديوك القادم على AYIN",
  "Choose the experience, add your file, and publish from one focused workspace. AYIN checks compatibility and prepares reliable playback automatically.":
    "اختر نوع الفيديو وأضف الملف، ثم راجع التفاصيل وانشره. يتحقق AYIN من توافق الملف ويجهز نسخة مناسبة للمشاهدة.",
  "Upload workflow": "خطوات رفع الفيديو",
  "Direct upload": "رفع مباشر",
  "Compatibility check": "فحص التوافق",
  "Playback processing": "تجهيز المشاهدة",
  "Choose the viewing experience": "اختر نوع الفيديو",
  "Pick how this upload should appear across AYIN before selecting the file.":
    "حدد طريقة عرض الفيديو قبل اختيار الملف.",
  "Video format": "نوع الفيديو",
  "Standard video": "فيديو عادي",
  "Full videos, episodes, tutorials and long-form stories.":
    "فيديوهات كاملة وحلقات وشروحات وقصص طويلة.",
  "Landscape + flexible": "أفقي أو أبعاد أخرى",
  "AYIN Clip": "مقطع AYIN",
  "Fast, vertical-first videos built for the Clips feed.": "فيديوهات قصيرة رأسية لصفحة المقاطع.",
  "Vertical-first": "رأسي",
  "Add your video": "أضف الفيديو",
  "Drag it here on desktop or open your library on mobile.": "اسحب الملف هنا أو اختره من جهازك.",
  "File selected": "تم اختيار الملف",
  "Drop your video here": "أفلت الفيديو هنا",
  "Select a video to upload": "اختر فيديو لرفعه",
  "Drag & drop a file here, or browse your device.": "اسحب الملف وأفلته هنا أو اختره من جهازك.",
  "Preparing your creator workspace…": "جارٍ تحميل مساحة المنشئ…",
  "Checking…": "جارٍ الفحص…",
  "Choose another": "اختر ملفًا آخر",
  "Browse video": "اختيار فيديو",
  "MP4, MOV, MKV, WebM and other common video formats": "MP4 وMOV وMKV وWebM وصيغ الفيديو الشائعة",
  "Finish your video": "أكمل تفاصيل الفيديو",
  "Review the essentials while AYIN completes the upload and playback preparation.":
    "راجع التفاصيل بعد تأكيد الرفع وتجهيز نسخة المشاهدة.",
  Title: "العنوان",
  "Give your video a clear title": "اكتب عنوانًا واضحًا للفيديو",
  "Upload status": "حالة الرفع",
  "Ready to publish": "جاهز للنشر",
  "Preparing playback": "جارٍ تجهيز المشاهدة",
  "Uploading video": "جارٍ رفع الفيديو",
  "Upload progress": "تقدم الرفع",
  "Advanced settings": "إعدادات إضافية",
  "Optional metadata, publishing controls and thumbnail · SEO stays automatic":
    "بيانات إضافية وخيارات النشر والصورة المصغرة",
  Description: "الوصف",
  "Tell viewers what this video is about": "اشرح للمشاهدين محتوى الفيديو",
  Visibility: "إتاحة الفيديو",
  Public: "عام",
  Unlisted: "غير مدرج",
  Private: "خاص",
  Schedule: "موعد النشر",
  "Allow comments": "السماح بالتعليقات",
  Thumbnail: "الصورة المصغرة",
  "Thumbnail suggestions appear when they are available.": "ستظهر اقتراحات الصور عند توفرها.",
  "Custom thumbnail saved": "تم حفظ الصورة المخصصة",
  "Upload a custom JPG or PNG": "اختر صورة JPG أو PNG",
  "By publishing, you confirm that you own this video or have all rights and permissions required to publish it on AYIN.":
    "بالنشر، تؤكد أنك تملك الفيديو أو لديك جميع الحقوق والتصاريح اللازمة لنشره على AYIN.",
  "Save details": "حفظ التفاصيل",
  Published: "تم النشر",
  "Publishing…": "جارٍ النشر…",
  "Publish video": "نشر الفيديو",
  Ready: "جاهز",
  Queued: "في الانتظار",
  Processing: "جارٍ التجهيز",
  Failed: "تعذر التجهيز",
  "Not started": "لم يبدأ",
  "Your video is uploading…": "جارٍ رفع الفيديو…",
  "Upload and processing complete. Your video is ready to publish.":
    "اكتمل الرفع والتجهيز. الفيديو جاهز للنشر.",
  "Upload complete. AYIN is preparing a reliable playback version in the background.":
    "اكتمل الرفع. يجري AYIN تجهيز نسخة مناسبة للمشاهدة.",
  "Drop one supported video file to start an upload.":
    "اسحب ملف فيديو واحدًا بصيغة مدعومة لبدء الرفع.",
  "Processing complete. This video is ready to publish.": "اكتمل التجهيز. الفيديو جاهز للنشر.",
  "Playback is not ready. The video remains saved in Studio; check its status before publishing.":
    "نسخة المشاهدة غير جاهزة. الفيديو محفوظ في الاستوديو؛ راجع حالته قبل النشر.",
  "Processing status is temporarily unavailable. Retry checking its status.":
    "تعذر تحميل حالة التجهيز مؤقتًا. أعد التحقق من الحالة.",
  "Check the title, schedule and advanced metadata before saving.":
    "راجع العنوان وموعد النشر والبيانات الإضافية قبل الحفظ.",
  "Video details saved.": "تم حفظ تفاصيل الفيديو.",
  "The save response could not be confirmed. Review this draft in Studio before writing again.":
    "تعذر تأكيد نتيجة الحفظ. راجع المسودة في الاستوديو قبل إجراء تعديل آخر.",
  "Choose a JPG or PNG thumbnail up to 5 MB.": "اختر صورة JPG أو PNG بحجم لا يتجاوز ٥ ميجابايت.",
  "Thumbnail saved.": "تم حفظ الصورة المصغرة.",
  "The thumbnail response could not be confirmed. Review this draft in Studio before writing again.":
    "تعذر تأكيد حفظ الصورة. راجع المسودة في الاستوديو قبل إجراء تعديل آخر.",
  "Check the title, schedule and advanced metadata before publishing.":
    "راجع العنوان وموعد النشر والبيانات الإضافية قبل النشر.",
  "Video scheduled. Opening your Studio content…": "تمت جدولة الفيديو. جارٍ فتح محتوى الاستوديو…",
  "Published privately. Opening your Studio content…":
    "نُشر الفيديو بشكل خاص. جارٍ فتح محتوى الاستوديو…",
  "Published. Opening your video…": "تم النشر. جارٍ فتح الفيديو…",
  "Publication could not be confirmed. Review this video's status in Studio before publishing again.":
    "تعذر تأكيد نتيجة النشر. راجع حالة الفيديو في الاستوديو قبل النشر مجددًا.",
  "Upload could not be confirmed. Review your saved uploads in Studio before starting again.":
    "تعذر تأكيد الرفع. راجع فيديوهاتك المحفوظة في الاستوديو قبل البدء مجددًا.",
  "The upload response could not be verified. Review this upload in Studio before trying again.":
    "تعذر التحقق من رد الرفع. راجع الفيديو في الاستوديو قبل المحاولة مجددًا.",
  "Your creator workspace could not be loaded.": "تعذر تحميل مساحة المنشئ.",
  "Retry loading workspace": "إعادة تحميل المساحة",
  "Manage saved videos": "إدارة الفيديوهات المحفوظة",
  "Review saved uploads in Studio": "مراجعة الفيديوهات المحفوظة في الاستوديو",
  " · The last response is uncertain; further writes are paused.":
    " · لم تتأكد نتيجة الطلب الأخير؛ تم إيقاف التعديلات التالية.",
  "Check processing status": "التحقق من حالة التجهيز",
  "Leave this upload? Unsaved changes and local file progress will be lost. Saved drafts remain in Studio.":
    "هل تريد مغادرة صفحة الرفع؟ ستفقد التعديلات غير المحفوظة وتقدم الملف المحلي. تظل المسودات المحفوظة في الاستوديو.",
  "Finalizing upload…": "جارٍ تأكيد الرفع…",
  "Connection paused. Retrying the upload safely…": "توقف الاتصال. جارٍ إعادة إرسال الجزء بأمان…",
  "Uploading video…": "جارٍ رفع الفيديو…",
  Tags: "الوسوم",
  "Up to 20 tags, 40 characters each. Separate tags with commas.":
    "حتى ٢٠ وسمًا، و٤٠ حرفًا لكل وسم. افصل الوسوم بفواصل.",
  Category: "التصنيف",
  "Not set": "غير محدد",
  Entertainment: "ترفيه",
  Education: "تعليم",
  Gaming: "ألعاب",
  Music: "موسيقى",
  News: "أخبار",
  Sports: "رياضة",
  Technology: "تقنية",
  Lifestyle: "أسلوب حياة",
  "Film & animation": "أفلام ورسوم متحركة",
  Other: "أخرى",
  "Primary language": "اللغة الرئيسية",
  "Recording date": "تاريخ التسجيل",
  "Content type": "نوع المحتوى",
  "Creator video (default)": "فيديو منشئ (افتراضي)",
  Movie: "فيلم",
  Documentary: "وثائقي",
  "Rights basis": "أساس حقوق النشر",
  "Standard authorization": "التصريح المعتاد",
  "I own it": "أملك المحتوى",
  Licensed: "مرخص",
  Authorized: "مصرح به",
  "Public domain": "ملكية عامة",
  "Rights note": "ملاحظة الحقوق",
  "Optional license or rights note": "ملاحظة اختيارية حول الترخيص أو الحقوق",
  "Rights expiration": "انتهاء الحقوق",
  "Optional distribution-rights expiry. Channel owner only in Studio.":
    "موعد اختياري لانتهاء حقوق التوزيع، يحدده مالك القناة.",
  "Series title": "السلسلة أو الحلقة",
  "Optional series title": "عنوان السلسلة (اختياري)",
  "Season number": "رقم الموسم",
  "Episode number": "رقم الحلقة",
  "Maturity level": "الفئة العمرية للمحتوى",
  General: "عام",
  Teen: "للمراهقين",
  Mature: "للبالغين",
  "Age restriction": "تقييد العمر",
  "None (default)": "بلا تقييد (افتراضي)",
  "13 and older": "١٣ عامًا فأكثر",
  "18 and older": "١٨ عامًا فأكثر",
  "Set the minimum audience age for this video.": "حدد الحد الأدنى لعمر جمهور الفيديو.",
  "Allowed territories": "الدول المسموح بها",
  "ISO two-letter country codes. Leave allowed and blocked lists empty for worldwide availability.":
    "رموز الدول من حرفين. اترك قائمتي السماح والحظر فارغتين للإتاحة عالميًا.",
  "Blocked territories": "الدول المحظورة",
  "Server-side playback, search, discovery, SEO and Creator TV all enforce these restrictions.":
    "تطبق هذه القيود على المشاهدة والبحث والاكتشاف وCreator TV.",
  "Custom chapters": "فصول الفيديو",
  "One chapter per line: MM:SS Title or HH:MM:SS Title. Starts must increase.":
    "فصل في كل سطر: MM:SS العنوان أو HH:MM:SS العنوان. رتب أوقات البداية تصاعديًا.",
  "Ad-break preference": "تفضيل فواصل الإعلانات",
  "Platform default": "إعداد المنصة الافتراضي",
  Automatic: "تلقائي",
  "No creator-requested breaks": "بدون فواصل يطلبها المنشئ",
  "Custom preferred offsets": "أوقات مفضلة مخصصة",
  "Custom ad-break offsets": "أوقات فواصل الإعلانات",
  "Preferred times in seconds from the start.": "الأوقات المفضلة بالثواني من بداية الفيديو.",
};
export function uploadText(value: string, locale: Locale): string {
  return locale === "ar" ? (arabic[value] ?? value) : value;
}
